[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiosmtplib>=3.0.2",
    "asyncio>=3.4.3",
    "dnspython>=2.7.0",
    "requests>=2.32.3",
]
